services:
  clickhouse:
    image: 'clickhouse/clickhouse-server:25.5-alpine'
    container_name: 'clickhouse-rs-clickhouse-server'
    ports:
      - '18123:8123'
      - '19000:9000'
    environment:
      - CLICKHOUSE_USER=click
      - CLICKHOUSE_PASSWORD=click
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      # - ./clickhouse_config:/etc/clickhouse-server/config.d
      # - ./clickhouse_users:/etc/clickhouse-server/users.d