
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - RUST_LOG=info
    env_file:
      - .env 
    depends_on:
      - mongo

  mongo:
    build:
      context: docker
      dockerfile: mongo.Dockerfile
    environment:
      - MONGO_INITDB_DATABASE=events
    ports:
      - "27017:27017"
    volumes:
      - ./.mongo:/data/db
    restart: always
